name: Windows C++ Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: |
          # 필요한 경우 추가 패키지를 설치
          choco install cmake -y
          choco install ninja -y

      # 디버그 빌드
      - name: Configure CMake (Debug)
        run: cmake -B build/debug -G "Ninja" -DCMAKE_BUILD_TYPE=Debug

      - name: Build (Debug)
        run: cmake --build build/debug --config Debug

      # 릴리즈 빌드
      - name: Configure CMake (Release)
        run: cmake -B build/release -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        run: cmake --build build/release --config Release

      # 디버그 빌드에서 테스트 실행
      - name: Run Tests (Debug)
        run: ctest --test-dir build/debug --output-on-failure

      # 릴리즈 빌드에서 테스트 실행
      - name: Run Tests (Release)
        run: ctest --test-dir build/release --output-on-failure
